coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      app:  # declare a new status context "app"
        paths: "!test/"  # remove all files in "test/"
        target: 75%
    patch:
       default:
         enabled: no
