coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      app:  # declare a new status context "app"
        paths: "!test/"  # remove all files in "test/"
        target: 75%
    patch:
       default:
         # basic
         target: auto
         threshold: null
         base: auto
         # advanced
         branches: null
         if_no_uploads: error
         if_not_found: success
         if_ci_failed: error
         only_pulls: false
         flags: null
         paths: null
