[dependencies]
unicode-segmentation = "1.7.1"    # This crate provides Grapheme Cluster, Word and Sentence boundaries according to Unicode Stand…

[features]
grapheme = []

[package]
edition = "2018"
name = "reverse_string"
version = "1.2.0"

